### PR TITLE
[SD-1150] Do not return access token when user has not confirmed yet

### LINKED ISSUE #10720: Devise :confirmable process works, but api v2 /spree_oauth/token always returns the access_token ....even if user has not confirmed yet!
## Context

Setting up Spree::Auth::Config[:confirmable] = true enables the devise :confirmable property of the spree_user.
All emails and confirmations process works. 
However, EVEN IF THE USER HAS NOT CONFIRMED YET, he/she is apparently able to receive an access_token through the  /spree_oauth/token api (and therefore he is a functional logged user).

## Expected Behavior
The user should not be able to login if the email has not been confirmed, an error message should be displayed ("please confirm your email to login")

## Actual Behavior
The user receives the access token and is behaving as logged in

## Steps to Reproduce
1. Enable config -> Spree::Auth::Config[:confirmable] = true
2. Create a new user
3. use the /spree_oauth/token api v2 to retreive the token

### PR DESCRIPTION
**Pull request by agnieszkajacek**
JIRA: [SD-1150](https://spark-solutions.atlassian.net/browse/SD-1150)

Fixes https://github.com/spree/spree/issues/10720

### CODE REVIEW

File: api/config/initializers/doorkeeper.rb [hunk 1]
```diff
@@ -7,7 +7,8 @@
 
   resource_owner_from_credentials do
     user = Spree.user_class.find_for_database_authentication(email: params[:username])
-    user if user&.valid_for_authentication? { user.valid_password?(params[:password]) }
+
+    user if user&.active_for_authentication? && user&.valid_for_authentication? { user.valid_password?(params[:password]) }
```
Comment (damianlegawiec) [inline api/config/initializers/doorkeeper.rb:11]:
```suggestion
    return nil if user.nil?
    
    if defined?(Spree::Auth::Config) && Spree::Auth::Config[:confirmable] == true
       user if user.active_for_authentication? && user.valid_for_authentication? { user.valid_password?(params[:password]) }
    else 
       user if user&.valid_for_authentication? { user.valid_password?(params[:password]) }
    end
```

**Review by damianlegawiec — APPROVED** [review]
