### PR TITLE
[SD-1461] fix money_methods for ruby version < 2.7

### LINKED ISSUE #11326: ArgumentError (wrong number of arguments (given 1, expected 0)) on .display_total caused by display_money.rb concern
**Context**
I have recently updated from Spree 4.2.5 to Spree 4.3.0.rc3.

**Expected Behavior**
Load admin orders page successfully.

**Actual Behavior**
I am unable to load the admin orders page on login, due to the following error:
`ActionView::Template::Error (wrong number of arguments (given 1, expected 0)):`

I have tracked this down to the following line:
`<td><%= order.display_total.to_html %></td>`

Indeed, this appears to be a wider issue related to the money_methods method in the `Spree::DisplayMoney` concern, as calling:
`Spree::Order.last.display_total`
in the rails console raises the following:
`ArgumentError (wrong number of arguments (given 1, expected 0))`

**Possible Fix**
The issue appears to have been introduced in #11208 , as reverting back to the Spree::DisplayMoney concern in Spree 4.2.5 resolves the issue.

**Your Environment**
Spree 4.3.0.rc3
Ruby 2.6.7
Rails 6.0.3

Thanks again team!

### PR DESCRIPTION
**Pull request by KacperMekarski**
Added photo because in Travis we use use newer ruby versions:
https://github.com/spree/spree/blob/main/cli/lib/spree_cli/templates/extension/travis.yml#L17-L19

Screenshot 2021-09-30 at 16 49 59

I considered moving `send(*[method_name, **args_list].reject(&:blank?))` to `amount` private method & `default_opts.merge(opts).merge(args_list.slice(:currency)` to `options` private method, but decided that passing arguments further will make it look too complicated.

### CODE REVIEW

**Comment by damianlegawiec** [comment]
@KacperMekarski this breaks the ruby 3.0 build, also the title/description is wrong, this works on ruby 2, but only on 2.7+

**Comment by KacperMekarski** [comment]
@damianlegawiec tried another approach.
Checked again locally using 2.6.3 and it's working fine.

File: core/app/models/concerns/spree/display_money.rb [hunk 1]
```diff
@@ -27,7 +27,9 @@ def money_methods(*args)
           define_method("display_#{method_name}") do |**args_list|
             default_opts = respond_to?(:currency) ? { currency: currency } : {}
 
-            Spree::Money.new(send(method_name, **args_list), default_opts.merge(opts).merge(args_list.slice(:currency)))
+            amount = args_list.blank? ? send(method_name) : send(method_name, **args_list)
+
+            Spree::Money.new(amount, default_opts.merge(opts).merge(args_list.slice(:currency)))
```
Comment (KacperMekarski) [inline core/app/models/concerns/spree/display_money.rb:32]: Tried earlier:
`Spree::Money.new(send(*[method_name, **args_list].reject(&:blank?)), default_opts.merge(opts).merge(args_list.slice(:currency)))` but did not work for ruby 3.*

**Review by kgorazd — APPROVED** [review]
