### PR TITLE
Removes money deprecation warning

### LINKED ISSUE #9658: Ruby Money deprecations
```
[WARNING] The default rounding mode will change to `ROUND_HALF_UP` in the next major release. Set it explicitly using `Money.rounding_mode=` to avoid potential problems.
[WARNING] The default currency will change to `nil` in the next major release. Make sure to set it explicitly using `Money.default_currency=` to avoid potential issues
```

## Context

https://github.com/RubyMoney/money/blob/master/CHANGELOG.md#6135

## Expected Behavior
No deprecations should be raised

## Actual Behavior
Deprecations are raised

## Possible Fix
Update https://github.com/spree/spree/blob/master/core/lib/spree/money.rb

## Steps to Reproduce
1. `bundle update`
2. Run the tests on CI

### PR DESCRIPTION
**Pull request by PSzyszkaSpark**
Removes money deprecation warning by setting default currency and default rounding mode. Fixes https://github.com/spree/spree/issues/9658

### CODE REVIEW

File: core/lib/spree/money.rb [hunk 1]
```diff
@@ -62,6 +65,15 @@ def ==(obj)
       money == obj.money
     end
 
+    def use_default_currency(options)
+      currency = options[:currency] || Spree::Config[:currency]
```
Comment (damianlegawiec) [inline core/lib/spree/money.rb]:
```suggestion
      currency = Spree::Store.default.default_currency || Spree::Config[:currency]
```

**Review by damianlegawiec — CHANGES_REQUESTED** [review]

**Review by damianlegawiec — APPROVED** [review]
