### PR TITLE
Use column_fallback plugin for storing default locale's translations in original columns

### LINKED ISSUE #12019: Same Taxonomies in different stores
## Context
Same Taxonomies in different stores, rails raise an error:

ActiveRecord::RecordNotUnique (PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "unique_permalink_per_locale"
DETAIL:  Key (locale, permalink)=(en, categories) already exists.
):

Default store has a taxonomy named 'Categories', change to other store again create a taxonomy named 'Categories', then raise an error like above. These store are same locale 'en' but different currency and VAT rules.

## Expected Behavior
Different stores had same Taxonomies.

## Actual Behavior
Server error 500

## Possible Fix
Maybe taxonomies can apply to all stores.

## Steps to Reproduce
1. Create a taxonomy in default store named 'Categories'
2. Change to other store, same locale different currency and VAT zone, like US and UK country
3. Again Create a taxonomy in default store named 'Categories'

## Your Environment
4.8.0.Beta

### PR DESCRIPTION
**Pull request by mad-eel**
Scope:
* Use original columns for the translatable fields in the default locale
* Remove migrations for transferring and deleting translatable data
* Fixes https://github.com/spree/spree/issues/12019

### CODE REVIEW

File: core/lib/spree/core/controller_helpers/locale.rb [hunk 1]
```diff
@@ -28,6 +28,10 @@ def set_fallback_locale
           Spree::Locales::SetFallbackLocaleForStore.new.call(store: current_store)
         end
 
+        def default_locale
```
Comment (mad-eel) [inline core/lib/spree/core/controller_helpers/locale.rb:31]: @damianlegawiec Shouldn't we assign the `default_locale` to  `I18n.default_locale` here: https://github.com/spree/spree/blob/main/core/lib/spree/core/controller_helpers/locale.rb#L21?

If a store has the `default_locale` set to `pl` then the `current_locale` will also be `pl` (unless picked otherwise). So we're still not using any translations and the `I18n.default_locale` should also be `pl`.

**Review by damianlegawiec — APPROVED** [review]

**Comment by pkatek** [comment]
@damianlegawiec  @mad-eel  But here's where the error went :/
See that the old migrations have been removed in the application and there is no unique_permalink_per_locale for new stores, but for old stores that are updating, it is already gone because they have a migration that assumes this change installed. And now there is a problem because I have this index set up unique_permalink_per_locale in spree_taxon_translations, to fix it now I have to do my own migration which will remove the indicated indexes and this will cause problems with other parameters in the future. In the same PR, there were also changes regarding the name and other translation parameters. So there has been a huge discrepancy between the store I had on 4.7. But we have a problem.

**Comment by pkatek** [comment]
As a general rule, migrations must not be removed in applications. You just need to add a new one that removes the previous change. Currently, if someone has created a store, they can't fix it without reinstalling the store.

**Comment by pkatek** [comment]
`class RemoveUniquePermalinkPerLocaleIndexFromSpreeTaxonTranslations < ActiveRecord::Migration[7.1]
  def self.up
    if index_exists?(:spree_taxon_translations, :unique_permalink_per_locale, name: 'unique_permalink_per_locale')
      remove_index :spree_taxon_translations, name: 'unique_permalink_per_locale'
    end
  end

  def self.down
    add_index :spree_taxon_translations, [:locale, :permalink], unique: true, name: 'unique_permalink_per_locale', if_not_exists: true
  end
end
`
