### PR TITLE
Fix variant positions in admin panel

### LINKED ISSUE #9614: It's not possible to change position of VARIANT, IMAGES and PROPERTIES on the list in Admin panel
It's not possible to change the position of the element on the list in the Admin panel. While trying to do this, 422 error will occur in Devtools/Network

## Steps to Reproduce

1. Login as Admin and go to admin panel
2. Move to Products -> Specific product -> Variants/Images/Properties
3. Try to move any element of the list
4. refresh the page
5. Observe issue

## Your Environment

* Version used: 4.0

### PR DESCRIPTION
**Pull request by AleksandraKaminska**
Fixes https://github.com/spree/spree/issues/9614

### CODE REVIEW

File: backend/app/controllers/spree/admin/resource_controller.rb [hunk 1]
```diff
@@ -69,7 +69,7 @@ def update_positions
     end
 
     respond_to do |format|
-      format.js { render plain: 'Ok' }
+      format.js { render status: :ok, plain: nil }
     end
```
Comment (damianlegawiec) [inline backend/app/controllers/spree/admin/resource_controller.rb]: @AleksandraKaminska we can replace this entire block to just

```ruby
head :ok
```

**Review by damianlegawiec — APPROVED** [review]
