### PR TITLE
Set fallback locale for Mobility based on current store

### LINKED ISSUE #11899: undefined method `to_url` for nil:NilClass when creating taxonomy
My spree instance is throwing `undefined method 'to_url' for nil:NilClass`

## Context
It's happening when I'm trying to create a taxonomy either using admin panel or directly via console. Name of the taxonomy is being provided as expected.

## Actual Behavior
image

## Steps to Reproduce
1. Create a store
2. Set it's default locale to PL
3. Set supported locales to EN and DE
4. Try to create a new taxonomy

## Your Environment

* Version used: 4.6.0
* Gemfile and Gemfile.lock as text in a Gist: https://gist.github.com/mbajur/511555171fefc967bb67144051a2166a

### PR DESCRIPTION
**Pull request by rafalcymerys**
Fixes #11899

### CODE REVIEW

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb [hunk 1]
```diff
@@ -0,0 +1,17 @@
+module Spree
+  module Locales
+    class SetFallbackLocaleForStore
+      def call(store:)
+        store_default_locale = store.default_locale
+        fallbacks = store.supported_locales_list.each_with_object({}) do |locale, object|
+          object[locale] = [store_default_locale]
+        end
```
Comment (kshalot) [inline core/app/services/spree/locales/set_fallback_locale_for_store.rb:8]: You can also consider doing:
```suggestion
        fallbacks = store.supported_locales_list.to_h { |locale| [locale, [store_default_locale]] }
```

File: core/lib/mobility/plugins/store_based_fallbacks.rb [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+        end
+      end
+
+      private
+
+      module BackendInstanceMethods
+        def read(locale, fallback: true, **kwargs)
+          return super(locale, **kwargs) if !fallback || kwargs[:locale]
+
+          locales = fallback == true ? Mobility.store_based_fallbacks.value[locale] : [locale, *fallback]
```
Comment (kshalot) [inline core/lib/mobility/plugins/store_based_fallbacks.rb:34]: There's already a `!fallback` check above so you know for sure that it's `true` here. `locales` will always be equal to:
```rb
Mobility.store_based_fallbacks.value[locale]
```

File: core/lib/mobility/plugins/store_based_fallbacks.rb [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+          locales.each do |fallback_locale|
+            value = super(fallback_locale, **kwargs)
+            return value if Util.present?(value)
+          end
+
+          super(locale, **kwargs)
```
Comment (kshalot) [inline core/lib/mobility/plugins/store_based_fallbacks.rb:40]: I don't get this part. The method gets a `locale` positional argument, but also a `locale` keyword argument. Shouldn't the logic be something in the lines of:
1. Check whether a translation exists for `locale`
2. If it exists - return it.
3. If it doesn't exist then try to use fallback.

And here I see that the fallback is calculated first, and only then the original locale in the `super(locale, **kwargs)` line. The first line that short-circuits if the kwarg is set is also confusing. What's the difference between the keyword argument and the positional argument? I guess it's some Mobility internal so in our codebase it looks a bit muddy.

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+
+        fallbacks_class = I18n::Locale::Fallbacks
+        fallbacks_instance = fallbacks_class.new(fallbacks)
+
+        Mobility.store_based_fallbacks.value = fallbacks_instance
```
Comment (kshalot) [inline core/app/services/spree/locales/set_fallback_locale_for_store.rb:13]: Maybe we could abstract this into Mobility in some way? I mean not explicitly set the instance variable on the `Mobility` singleton class. My problem with this now is that it leaks the way we store the fallback in a way. Doing a 
```rb
Mobility.set_store_fallback(fallbacks_instance)
```
would intuitively make more sense to me, since no implementation details are exposed.

**Review by kshalot — CHANGES_REQUESTED** [review]

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb (hunk 1 above)
Comment (rafalcymerys) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb:8]: Hm, isn't it more explicit and clear when we do `each_with_object`?

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+  module Locales
+    class SetFallbackLocaleForStore
+      def call(store:)
+        store_default_locale = store.default_locale
+        fallbacks = store.supported_locales_list.each_with_object({}) do |locale, object|
+          object[locale] = [store_default_locale]
+        end
+
+        fallbacks_class = I18n::Locale::Fallbacks
+        fallbacks_instance = fallbacks_class.new(fallbacks)
```
[the remark this answers is not in the document]
Comment (rafalcymerys) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb:11]: That were some leftovers from the original implementation in mobility. Good point :)

File: core/lib/mobility/plugins/store_based_fallbacks.rb (hunk 2 above)
Comment (rafalcymerys) [reply core/lib/mobility/plugins/store_based_fallbacks.rb:34]: That's a leftover from the stock fallbacks implementation, good point :)

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb (hunk 1 above)
Comment (kshalot) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb:8]: I don't have a strong preference for either to be honest. `each_with_object` probably looks more familiar to most readers. In defense of `#to_h` - to me it's clear in the way it just deals with simple `[key, value]` objects instead of having this "state" object that's initialised in a loop. I like the original as well though, hence my original comment mentioning the suggestion as something to consider.

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb (hunk 4 above)
Comment (kshalot) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb:13]: Yeah, a getter and setter would do the job.

File: core/lib/mobility/plugins/store_based_fallbacks.rb (hunk 3 above)
Comment (rafalcymerys) [reply core/lib/mobility/plugins/store_based_fallbacks.rb:46]: @kshalot that's what this implementation does. 

The logic is as follows:
1. If a specific locale is requested or fallback is disabled - skip the fallbacks mechanism and read the value without the fallbacks in specified locale
2. Iterate through the fallbacks for requested locale. This list always starts with the locale itself, so e.g. fallbacks['en'] = ['en', (other locales that are configured)]. If a value is found for any of them, return it 
3. If this didn't return any result, read the value without the fallbacks for specified locale

The signature of this function is not the most clear one, but I'd prefer to keep it, not to break other mobility plugins that need to work alongside it

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb (hunk 4 above)
Comment (rafalcymerys) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb]: Please take a look again

File: api/spec/requests/spree/api/v2/storefront/taxons_spec.rb [hunk 6]
```diff
@@ -267,6 +267,7 @@
       let(:translated_slug) { 'test_slug_es' }
 
       before do
+        Spree::Locales::SetFallbackLocaleForStore.new.call(store: store2)
```
Comment (kshalot) [inline api/spec/requests/spree/api/v2/storefront/taxons_spec.rb:270]: Now that I'm looking at the tests - it would probably be wise to cover this fallback functionality with tests in general. I guess what we are missing is:
1. Test whether the locale controller helper sets the fallback when `current_store` is present.
2. Test whether the fallback plugin itself works as intended.

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb [hunk 7]
```diff
@@ -0,0 +1,17 @@
+module Spree
+  module Locales
+    class SetFallbackLocaleForStore
+      def call(store:)
+        store_default_locale = store.default_locale
+        fallbacks = store.supported_locales_list.each_with_object({}) do |locale, object|
+          object[locale] = [store_default_locale]
```
Comment (kshalot) [inline core/app/services/spree/locales/set_fallback_locale_for_store.rb:7]: What if there's only one locale? Will it still try to fallback using itself? This would obviously be redundant.

**Review by kshalot — CHANGES_REQUESTED** [review]

File: api/spec/requests/spree/api/v2/storefront/taxons_spec.rb (hunk 6 above)
Comment (rafalcymerys) [reply api/spec/requests/spree/api/v2/storefront/taxons_spec.rb]: 1. This is covered e.g. by the requests tests for the API. I forgot to remove setting it manually here, it works without it. I moved away from generating the slugs with fallbacks manually, and it now fully relies on mobility, so the old assertions check this behavior end-to-end now.
2. I added two specs for that

File: core/app/services/spree/locales/set_fallback_locale_for_store.rb (hunk 7 above)
Comment (rafalcymerys) [reply core/app/services/spree/locales/set_fallback_locale_for_store.rb:7]: It won't change anything then. I18n::Locale::Fallbacks consolidates duplicate entries in the list of fallbacks, and the first "fallback" on the list for each locale is the actual locale. Only the later entries denote actual fallbacks in case the requested one is not present.

File: core/lib/mobility/plugins/store_based_fallbacks.rb [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+    module StoreBasedFallbacks
+      extend ::Mobility::Plugin
+
+      default true
+      requires :backend, include: :before
+
+      # Applies fallbacks plugin to attributes. Completely disables fallbacks
+      # on model if option is +false+.
+      included_hook do |_, backend_class|
+        unless options[:fallbacks] == false
```
[the remark this answers is not in the document]
Comment (rafalcymerys) [reply core/lib/mobility/plugins/store_based_fallbacks.rb:29]: It would be, but I'm not sure about the interface here :) After this change it will behave differently for a falsey value (e.g. nil), and I think Mobility's default fallbacks plugin would work if that option is not set. Only setting it explicitly to false disabled it.

File: core/lib/mobility/plugins/store_based_fallbacks.rb (hunk 3 above)
Comment (rafalcymerys) [reply core/lib/mobility/plugins/store_based_fallbacks.rb:44]: I did some further investigation on that, it seems that Mobility's internals call it like `read(locale, locale: true)`. Example here: https://github.com/shioyama/mobility/blob/master/lib/mobility/plugins/active_model/dirty.rb 
So the kwargs[:locale] can be true/false and it has a different semantic. 

This part of the implementation is a slightly modified implementation of the default fallbacks plugin, so I kept the behavior in this case the same.

File: core/app/models/spree/taxon.rb [hunk 9]
```diff
@@ -66,10 +67,12 @@ class Taxon < Spree::Base
 
       def set_permalink
         parent = translated_model.parent
+        name_with_fallback = name || translated_model.name
```
Comment (kshalot) [inline core/app/models/spree/taxon.rb:70]: Just a question - this refers to the `name` in the translation and when it's not set it falls back to the model's `name` which kicks in the whole fallback mechanism, right?

File: core/app/models/concerns/spree/translatable_resource_slug.rb [hunk 10]
```diff
@@ -4,12 +4,10 @@ module TranslatableResourceSlug
 
     included do
       def localized_slugs_for_store(store)
-        localized_slugs = Hash[translations.pluck(:locale, :slug)]
-        default_locale = store.default_locale
         supported_locales = store.supported_locales_list
 
         supported_locales.each_with_object({}) do |locale, hash|
-          hash[locale] = localized_slugs[locale] || localized_slugs[default_locale]
+          hash[locale] = I18n.with_locale(locale) { slug }
```
Comment (kshalot) [inline core/app/models/concerns/spree/translatable_resource_slug.rb:10]: Technically, we could loosen the contract between this module and the including module by introducing a dependency on `FriendlyId`. I think you can access the `slug_column` config value by doing `model.friendly_id_config.slug_column`. Not great either, but it popped in my mind after seeing that you had to add a `slug` alias to the Taxon model just so this works. Something to consider in the future maybe

**Review by kshalot — APPROVED** [review]
Just three remarks (one actual question in the spec).

Apart from that I'd say it looks good 👍 ✅ :shipit:

File: core/spec/services/spree/locales/set_fallback_locale_for_store_spec.rb [hunk 11]
```diff
@@ -0,0 +1,37 @@
...
+    let(:command) { described_class.new }
+
+    describe '#call' do
+      let(:store) { create(:store, default_locale: 'pl', supported_locales: 'en,de,pl') }
+      let(:product) { create(:product, name: 'test') }
+
+      let(:name_en) { 'name en' }
+      let(:name_pl) { 'name pl' }
+
+      let!(:translation_en) { product.translations.find_or_create_by(locale: 'en') { |e| e.name = name_en } }
```
[the remark this answers is not in the document]
Comment (kshalot) [reply core/spec/services/spree/locales/set_fallback_locale_for_store_spec.rb:14]: Or is it there to demonstrate that the fallback will be the `default_locale` and not some random locale?

File: core/app/models/spree/taxon.rb (hunk 9 above)
Comment (rafalcymerys) [reply core/app/models/spree/taxon.rb:70]: Exactly

File: core/spec/services/spree/locales/set_fallback_locale_for_store_spec.rb (hunk 11 above)
[the remark this answers is not in the document]
Comment (rafalcymerys) [reply core/spec/services/spree/locales/set_fallback_locale_for_store_spec.rb:14]: We want to check whether it falls back to a specific locale (in this case `pl`), without taking the `en` value (which is by default set as I18n.default_locale and Mobility uses it as a default for fallbacks)

File: core/app/models/concerns/spree/translatable_resource_slug.rb (hunk 10 above)
Comment (rafalcymerys) [reply core/app/models/concerns/spree/translatable_resource_slug.rb:10]: We wanted to unify the naming of the `permalink` -> `slug` column anyway, as it's a bit confusing right now. Technically all of them should be called `slug`, as `permalink` refers to the whole URL, including domain name.
