### PR TITLE
API v2 Set order state to address if billing or shipping  address is updated

### LINKED ISSUE #10276: Shipments are not updated when Shipping Address Changes
If a user changes his shipping address in checkout, the shipment keeps the old address. Also the shipping rates are not updated if the address changes.

Also: If the amount changes, price sacks might not be recalculated. (I'm investigating this and create a new ticket if that persists)

## Expected Behavior
When changing the shipping country (or tax zone) shipment should get updated since prices might change.

## Actual Behavior
Old address is used and shipments are not recalculated

## Possible Fix
Shipping Address change on order should also check if a new shipment needs to be generated / the shipment needs to be updated.

## Steps to Reproduce
I'm using API v2, but I also can reproduce this in admin.

**API V2**
1. Create cart, add product, ...
2. Checkout: Set Shipping Address
3. Request shipping rates
4. Change shipping address
5. Request shipping rates again
Result: Shipping rates should be the same. In Database you should also see, that the ID is the old one (from request 2)

**Backend**
1. Go to order that is not complete
2. Check shipping rate
3. change country for shipment and save
4. check shipping rate again

Of course you need to setup different shipping rates for those countries to see the effect.

## Your Environment
* Version used: Latest spree from master

### PR DESCRIPTION
**Pull request by johannboutet**
Fix #10276 

When updating the shipping or billing address for an order, we need to also reset the state to address so we can recalculate tax and shipping rates.

### CODE REVIEW

File: core/app/services/spree/checkout/update.rb [hunk 1]
```diff
@@ -4,8 +4,11 @@ class Update
       prepend Spree::ServiceModule::Base
 
       def call(order:, params:, permitted_attributes:, request_env:)
-        params = replace_country_iso_with_id(params, 'ship') if address_with_country_iso_present?(params, 'ship')
-        params = replace_country_iso_with_id(params, 'bill') if address_with_country_iso_present?(params, 'bill')
+        ship_changed = address_with_country_iso_present?(params, 'ship')
+        bill_changed = address_with_country_iso_present?(params, 'bill')
+        params = replace_country_iso_with_id(params, 'ship') if ship_changed
+        params = replace_country_iso_with_id(params, 'bill') if bill_changed
+        order.state = 'address' if ship_changed || bill_changed
```
Comment (damianlegawiec) [inline core/app/services/spree/checkout/update.rb:11]:
```suggestion
        order.state = 'address' if (ship_changed || bill_changed) && @order.checkout_sptes.include?('address')
```

**Review by damianlegawiec — COMMENTED** [review]
Thanks @johannboutet - this is a valid approach, could you include the small comment I've left? Thyank you!

**Comment by johannboutet** [comment]
@damianlegawiec good catch with the additional check, I just fixed a small typo ;)

After more testing with the other checkout steps, I think we may need a similar logic for the delivery step. If a customer decides to change the selected shipping rate, the order needs to go back to delivery state to recalculate the tax amount on the shipping cost. Probably something like this:

```
def call(order:, params:, permitted_attributes:, request_env:)
  ...
  order.state = 'delivery' if selected_shipping_rate_present?(params) && order.has_checkout_step?('delivery')
  ...
end

def selected_shipping_rate_present?(params)
  shipments_attributes = params.dig(:order, :shipments_attributes)
  return false unless shipments_attributes

  shipments_attributes.any? { |s| s.selected_shipping_rate_id }
end
```

What do you think? I can add it to this PR, or open another one, as you prefer.

**Comment by damianlegawiec** [comment]
Hey @johannboutet let's merge this one and create another for the delivery step - also good catch! :)
