### PR TITLE
use relative path for storefront countries request

### LINKED ISSUE #9540: Address form is broken when Spree is mounted at a path different than "/"
## Context

The state search is broken when you mount Spree (and the API) at a different path, due to https://github.com/spree/spree/commit/966386c200175473d04d3449718fd985a6910474#diff-ffaffad1bc65f5b9af7952c7952570aaR9

## Expected Behavior

Changing country should fetch associated states.

## Actual Behavior

Server responds with 404.
```
Routing Error

No route matches [GET] "/api/v2/storefront/countries/4"
```

## Possible Fix

Generate a correct url and use it instead of a hardcoded version.

## Steps to Reproduce

1. Mount Spree at "/store"
2. Launch the server
3. Go through the checkout process, select a country and try to select a state

## Your Environment

* Version used:
* Gemfile and Gemfile.lock as text in a Gist:
* Any relevant stack traces ("Full trace" preferred):

### PR DESCRIPTION
**Pull request by chhlga**
Fixes #9540

### CODE REVIEW

File: frontend/app/assets/javascripts/spree/frontend/checkout/address.js [hunk 1]
```diff
@@ -6,7 +6,7 @@ Spree.ready(function ($) {
         if (countryId != null) {
           if (Spree.Checkout[countryId] == null) {
             $.ajax({
-              async: false, method: 'GET', url: '/api/v2/storefront/countries/' + countryId + '?include=states', dataType: 'json'
+              async: false, method: 'GET', url: Spree.pathFor('/api/v2/storefront/countries/') + countryId + '?include=states', dataType: 'json'
```
Comment (damianlegawiec) [inline frontend/app/assets/javascripts/spree/frontend/checkout/address.js]:
```suggestion
              async: false, method: 'GET', url: Spree.pathFor('/api/v2/storefront/countries/' + countryId + '?include=states'), dataType: 'json'
```

**Review by damianlegawiec — APPROVED** [review]
