### PR TITLE
Remove state_id or state_name  #6598

### LINKED ISSUE #6598: Address.state_id not cleared when changed to a country without states
To reproduce:
- `/checkout/address`: enter United States, select a state, and fill out address, click "Save and Continue"
- from `/checkout/delivery`, click link to go back to `/checkout/address`
- select new country (ex: Chile), which hides the state select box.
- "Save and Continue" does not submit the state_id, but the value is preserved in the spree_address model instance.

This can cause problems with making certain shipping methods available (if they are available based on State-based Zones) when they are not meant for that country. Example: Given Free US Shipping for some US states, now customer can get free shipping to Chile.

### PR DESCRIPTION
**Pull request by tanmay3011**
Fixes #6598
- Clear state_name or state_id incase addresses country is changed to a country without states
- Indent private methods

### CODE REVIEW

File: core/app/models/spree/address.rb [hunk 1]
```diff
@@ -97,49 +99,70 @@ def require_zipcode?
...
+
+    def clear_invalid_state_entities
+      if state.present? && (state.country != country)
+        clear_state
+      elsif state_name.present? && !country.states_required? && country.states.empty?
+        clear_state_name
+      end
+    end
+
+    def state_validate
```
Comment (krzysiek1507) [inline core/app/models/spree/address.rb]: This method is too complicated and ugly. ;)

Comment (tanmay3011) [inline core/app/models/spree/address.rb]: @krzysiek1507  Yeah! It's very complicated. Will try to fix it in a separate PR a lot of features are associated with it.
